name: Check QA

on: push

jobs:
  blackduck:
    name: Run Black Duck Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Build with Maven
        id: build
        run: mvn clean install -DskipTests

      - name: Black Duck Full Scan
        uses: synopsys-sig/synopsys-action@v1.13.0
        env:
          DETECT_PROJECT_NAME: SKO-Connect_Services-Backend
          DETECT_ACCURACY_REQUIRED: "NONE"
        with:
          blackduck_url: ${{ secrets.BLACKDUCK_URL }}
          blackduck_token: ${{ secrets.BLACKDUCK_TOKEN }}
          blackduck_scan_full: true
          blackduck_args: "--detect.project.version.name=${{ github.ref_name }}"
          blackduck_scan_failure_severities: "BLOCKER,CRITICAL,MAJOR"
          blackduck_fixpr_enabled: false

  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "https://sonarqube.diconium.cloud"
        with:
          args: >
            -Dsonar.projectKey=SKO-Connect_Services-Backend
            -Dsonar.projectSources=.
            -Dsonar.verbose=true
