name: Push to Main Pipeline
run-name: Push to Main Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  call-branch-quality-workflow:
    uses: ./.github/workflows/aux_branch_quality.workflow.yml
    name: Branch Code Quality
    with:
      continue_on_error: false
      check_blackduck: true
      check_sonarqube: true
    secrets: inherit
  
  publish-deploy-prod:
    uses: ./.github/workflows/aux_publish_and_deploy.workflow.yml
    needs:
      - call-branch-quality-workflow
    name: Publish and Deploy Prod
    with:
      tag: release
      release: production
    secrets: inherit
